---
- name: Check package & process  on Linux hosts
  hosts: all 
  vars:
    target: "http"
    package_store_file: "/tmp/package-check.txt"
    store_host: "host1"
  tasks:
    - name: To check matched package and process
      ansible.builtin.shell: "echo Packages: $(rpm -qa |grep -i {{ target }}) ; echo Process: $( ps -eo '%c %a' |grep -i {{ target }} |grep -v grep)"
      ignore_errors: true  
      register: pkglist
    - name: Clean the oringinal stored file
      ansible.builtin.file:
        path: "{{ package_store_file }}"
        state: absent
      run_once: true
      delegate_to: localhost
    - debug:
        var: inventory_hostname+"\n"+pkglist.stdout
      delegate_to: localhost
    - name: To append the username in a file
      ansible.builtin.lineinfile:
        path: "{{ package_store_file }}"
        line: "{{ item }}:\n{{ hostvars[item].pkglist.stdout_lines|to_nice_yaml }}"
        create: true
        state: present
      run_once: true
      with_items: "{{ groups['all'] }}"
      delegate_to: localhost
    - name: copy package_store_file from local to another host
      ansible.builtin.copy:
        src: "{{ package_store_file }}"
        dest: "{{ package_store_file }}"
      run_once: true
      delegate_to: "{{ store_host }}"
      when: store_host is defined


