---
- name: Check services on Linux hosts
  hosts: all 
  vars:
    services_list: "crond sshd httpd vsftpd"
    store_file: "/tmp/svc-check.txt"
    store_host: "host1"
  tasks:
    - name: Check services status
      ansible.builtin.shell: |
        for service in {{ services_list }}; do
          systemctl is-active $service > /dev/null || echo  "$service not running" 
        done
      register: service_check
    - debug:
        var: service_check.stdout_lines
    - name: initialize empty list
      ansible.builtin.set_fact:
        my_list: []
    - name: set fact
      ansible.builtin.set_fact:
        my_list: "{{ my_list + [ item] }}"
        node_name: "{{ inventory_hostname }}"
      when: item != "active"
      loop: "{{service_check.stdout_lines}}"
    - debug:
        msg: "{{ node_name }}\n{{ my_list|to_nice_yaml }}" 
    - name: clean tmp files @all hosts
      ansible.builtin.file:
        path: "{{ store_file }}"
        state: absent
      delegate_to: localhost
    - name: save result
      ansible.builtin.shell: |
        echo -e "{{ node_name }}\n{{ my_list|to_nice_yaml }}" >> "{{ store_file }}"
      delegate_to: localhost
    - name: copy store_file from local to another host
      ansible.builtin.copy:
        src: "{{ store_file }}"
        dest: "{{ store_file }}"
      run_once: true
      delegate_to: "{{ store_host }}"
      when: store_host is defined
