---
- name: Check services on Linux hosts
  hosts: all 
  become: yes
  vars:
    services_list: "crond sshd httpd xxx abc vsftpd"
    store_file: "/tmp/svc-check.txt"
  tasks:
    - name: Check services status
      ansible.builtin.shell: |
        for service in {{ services_list }}; do
          systemctl is-active $service > /dev/null || echo  "$service not running" 
        done
      register: service_check
    - debug:
        var: service_check.stdout_lines
    - name: set fact 1
      ansible.builtin.set_fact:
        node_name: "{{ inventory_hostname }}"
    - name: initialize empty list
      ansible.builtin.set_fact:
        my_list: []
    - name: set fact 2
      ansible.builtin.set_fact:
        my_list: "{{ my_list + [ item] }}"
      when: item != "active"
      loop: "{{service_check.stdout_lines}}"
    - debug:
        msg: "{{ node_name }}\n{{ my_list|to_nice_yaml }}" 
    - name: clean tmp files @all hosts
      ansible.builtin.file:
        path: "{{ store_file }}"
        state: absent
      delegate_to: localhost
    - name: save result
      ansible.builtin.shell: |
        echo -e "{{ node_name }}\n{{ my_list|to_nice_yaml }}" >> "{{ store_file }}"
      delegate_to: localhost
