---
- name: This playbook will create a file
  hosts: all 
  vars:
    store_file: "/tmp/test-user.txt"
  tasks:
    - name: To check the uses - uid=0 or uid > 1000 
      ansible.builtin.shell: "cat /etc/passwd | awk -F: '$3>=1000||$3==0{print $1\": \"$3}'"
      register: userlist
    - name: Clean old file
      ansible.builtin.file:
        path: "{{ store_file }}"
        state: absent 
      run_once: true
      delegate_to: localhost
    - name: To append the username in a file
      ansible.builtin.lineinfile:
        path: "{{ store_file }}"
        line: "{{ item }}:\n{{ hostvars[item].userlist.stdout_lines|to_nice_yaml }}"
        create: true
        state: present
      with_items: "{{ groups['all'] }}"
      delegate_to: localhost

